### ISSUE TITLE
error in forecasts

### ISSUE THREAD

**Issue by bdkacz** [basking-in-the-sun2000/solar-logger#1]
Hello

I get follwing error :

Traceback (most recent call last):
  File "main.py", line 559, in <module>
    main()
  File "main.py", line 410, in main
    forcast_time = forcast()
  File "main.py", line 182, in forcast
    for x in r1.content['forecasts']:
KeyError: 'forecasts'

What I'm doing wrong ?

When I try get data manually via url https://api.solcast.com.au/rooftop_sites/772e-0d3d-66a8-6ed8/forecasts?format=json looks like there is data

**Comment by basking-in-the-sun2000** [comment]
Sorry didn't see this before. Could it be that you are being throttled or ran out of calls for the day?

If it happens again, let me know

**Comment by bdkacz** [comment]
Hi. After last update everything looks working ok :)
