### ISSUE TITLE
'forecast_array' is not defined

### ISSUE THREAD

**Issue by bdkacz** [basking-in-the-sun2000/solar-logger#13]
Hello

When software have  problem with getting  forecast for example " forecast 1 error: 'forecasts' " the software restarts and restarts - maybe is it possible to add option to ignore forecasts error and/or disable forecast future via config.py ?

**Comment by basking-in-the-sun2000** [comment]
just added that for the issue that javierin posted. Hope the current push will fix your problems. Just as a warning, the low production emails only work from 11 to 15 hours when the production drops to 0. 

Any reason you don't want to use the solecast forecasts?

**Comment by bdkacz** [comment]
For example now (I don't know how)  I exceed the 20 cal;ls/day  and...solar-logger give error and  don't write data from inverter to database :) So it is not "I don't want to use" but for example  solcast is down for maintance and we lost logging function :)

**Comment by basking-in-the-sun2000** [comment]
if you restarted the application multiple times, it can go over the limit. Most of the time I'm around 7 calls a day, but do go to 20 occasionally(!). Hope the patch will fix this for you. 

I was curious if someone didn't wanted to use it and for what reason.  Thanks for giving the logger a go :)

**Comment by bdkacz** [comment]
Las update solve the problem- thanks ;)
