### ISSUE TITLE
Huawei.py file missing ?

### ISSUE THREAD

**Issue by BelMaseto** [basking-in-the-sun2000/solar-logger#29]
Hi,

Great job, I've started my own integration project so I'll learn a lot from your code.

But seems that Huawei.py file is missing. It should have the inverter configuration, It's called from utils. Could you check this ?
Thanks in advance.

**Comment by verisgit** [comment]
Using the latest version of the code mine didn't create a Huawei.py either I had to create one manually from the default file. Not sure if that's intentional?
