### ISSUE TITLE
Told to install ISOLATE module - believe you mean ISODATE ?

### ISSUE THREAD

**Issue by craigcurtin-dev** [basking-in-the-sun2000/solar-logger#4]
In the Setup.MD file the instructions advise to pip3 install isolate - i think you mean isodate as i can not find the isolate package at all

Craig

**Comment by basking-in-the-sun2000** [comment]
lol

autocorrect, thanks for pointing it out. Will push a correction 

Hope everything else is a-ok

**Comment by craigcurtin-dev** [comment]
Just working through it now thanks – I am setting this up with a pair of Solis 5K inverters running it on a Ubuntu VM – so a few things to work through but getting there I think

Will know a bit more later tonight

Will revert back if any more issues or corrections

Craig

**Comment by basking-in-the-sun2000** [comment]
good luck. I hoped it won't be too much changing it. Tried to make it flexible, but probably there is some bias towards my inverter.

**Comment by craigcurtin-dev** [comment]
No worries – will see how I go plowing through it – very impressed with your dashboards etc.

I have the full Modbus map for the inverter so should be able to get a good map between the two – if I do get it working I will provide the updates so they can be included for others.

Craig

**Comment by basking-in-the-sun2000** [comment]
Closing the post. Hope you get the solis inverter working
