### ISSUE TITLE
influx autostart

### ISSUE THREAD

**Issue by verisgit** [basking-in-the-sun2000/solar-logger#41]
Something else I forgot to mention with settting_up.md

The step to enable influx for autostart on reboot didn't seem to work:

sudo service influxdb enable
influxdb: unrecognized service

**Comment by basking-in-the-sun2000** [comment]
seems they stopped using service and switched to systemctl. Will be changing it on the next commit

It will end up being as follows
```
sudo systemctl unmask grafana-server.service
sudo systemctl start grafana-server
sudo systemctl enable grafana-server.service

sudo systemctl unmask influxdb.service
sudo systemctl start influxdb
sudo systemctl enable influxdb.service
```

Thank
