### ISSUE TITLE
Question: Backups

### ISSUE THREAD

**Issue by verisgit** [basking-in-the-sun2000/solar-logger#50]
Hi there, just wondering what files/folders need to be backed up if I want to create a second copy in case my Pi fails. I'd hate to lose my historical data.

Also are there any particular folders to check for max file size or out of limit issues long term?

**Comment by basking-in-the-sun2000** [comment]
most is stored in influxdb. You would need to backup your db

**Comment by verisgit** [comment]
Where's that located based on the install steps?

Is it just /var/lib/data that I would need to backup or the meta and other folders also?

**Comment by basking-in-the-sun2000** [comment]
you shouldn't need to backup the folders. Dbs have a mechanism to backup the data

https://docs.influxdata.com/influxdb/v1.8/administration/backup_and_restore/

**Comment by verisgit** [comment]
Ah yes, I've setup a cron to do that. Thanks
